"""Fine-tune YOLO for tennis ball detection on blob crops.

Uses the dataset generated by prepare_yolo_crops.py.

Usage:
    python -m tools.train_blob_verifier [--data data/blob_crops/data.yaml] [--epochs 50]
"""

import argparse
from pathlib import Path


def train(
    data_yaml: str = "data/blob_crops/data.yaml",
    model_name: str = "yolo11n.pt",
    epochs: int = 50,
    imgsz: int = 128,
    batch: int = 32,
    freeze: int = 10,
    device: str = "0",
    output_dir: str = "model_weight",
) -> None:
    """Fine-tune YOLO on blob crop dataset."""
    from ultralytics import YOLO

    data_path = Path(data_yaml)
    if not data_path.exists():
        raise FileNotFoundError(
            f"Dataset config not found: {data_yaml}\n"
            "Run 'python -m tools.prepare_yolo_crops' first."
        )

    print(f"Loading base model: {model_name}")
    model = YOLO(model_name)

    print(f"Training on {data_yaml}")
    print(f"  epochs={epochs}, imgsz={imgsz}, batch={batch}, freeze={freeze}")

    results = model.train(
        data=str(data_path.resolve()),
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
        freeze=freeze,
        single_cls=True,
        device=device,
        project=output_dir,
        name="blob_verifier",
        exist_ok=True,
    )

    # Copy best weights
    best_path = Path(output_dir) / "blob_verifier" / "weights" / "best.pt"
    final_path = Path(output_dir) / "blob_verifier_yolo.pt"
    if best_path.exists():
        import shutil
        shutil.copy2(best_path, final_path)
        print(f"\nBest model saved to: {final_path}")
    else:
        print(f"\nTraining complete. Check {output_dir}/blob_verifier/ for results.")

    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Fine-tune YOLO blob verifier")
    parser.add_argument("--data", default="data/blob_crops/data.yaml")
    parser.add_argument("--model", default="yolo11n.pt", help="Base model")
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--imgsz", type=int, default=128)
    parser.add_argument("--batch", type=int, default=32)
    parser.add_argument("--freeze", type=int, default=10)
    parser.add_argument("--device", default="0")
    parser.add_argument("--output", default="model_weight")
    args = parser.parse_args()

    train(
        data_yaml=args.data,
        model_name=args.model,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        freeze=args.freeze,
        device=args.device,
        output_dir=args.output,
    )
